apiweb/apps/internal/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import url
from .views import LogoView, IndexView, ObservatoryView, AdressesView
from .views import ShowProfileView, CreateProfileView, EditProfileView
from .phonelist import TelephonelistView

handler500 = 'apiweb.apps.main.errorview.server_error'

urlpatterns = [
    url(r'^create/$',
        view=CreateProfileView.as_view(),
        name='create-profile'),
    url(r'^edit/$',
        view=EditProfileView.as_view(),
        name='edit-profile'),
    url(r'^show/$',
        view=ShowProfileView.as_view(),
        name='show-profile'),
    url(r'^logo/$',
        view=LogoView.as_view(),
        name='logo'),
    url(r'^observatory/$',
        view=ObservatoryView.as_view(),
        name='observatory'),
    url(r'^addresses/phonelist/$',
        view=TelephonelistView.as_view(),

        name='addresses-phonelist'),
    url(r'^addresses/$',
        view=AdressesView.as_view(),
        name='addresses'),
    url(r'^show/$',
        view=ShowProfileView.as_view(),
        name='show-profile'),
    url(r'^edit/$',
        view=EditProfileView.as_view(),
        name='edit-profile'),
    url(r'^create/$',
        view=CreateProfileView.as_view(),
        name='create-profile'),
    url(r'^$',
        view=IndexView.as_view(),
        name='index'),
]

apiweb/apps/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import include, url
from django.contrib import admin
import django.contrib.sitemaps.views
from .main.sitemap import sitemaps
from .main.views import MainView, HomeView, ScatterView, LowercaseView
from .main.views import SitemapView, AboutView, TwentyFourSevenView
import filebrowser.sites


admin.autodiscover()

urlpatterns = [
    url(r'^.*[A-Z]+.*$',
        view=LowercaseView.as_view(),
        name='redirect-uppercase'),

    url(r'^media/uploads/staff_meetings/',
        include('apiweb.apps.staffmeetings.media_urls')),

    url(r'^admin/filebrowser/',
        include(filebrowser.sites.site.urls)),

    #url(r'^admin/filebrowser/',
    #    include('filebrowser.urls', namespace='filebrowser')),
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # deprecated url(r'^admin/(.*)', admin.site.root, name='admin-root'),
    # to use new setup in templates, use {% url admin:index %}
    url(r'^admin/',
        include(admin.site.urls)),

    url(r'^news/',
        include('apiweb.apps.news.urls', namespace='news')),
    url(r'^people/',
        include('apiweb.apps.people.urls', namespace='people')),
    url(r'^education/',
        include('apiweb.apps.education.urls', namespace='education')),
    url(r'^institute/',
        include('apiweb.apps.institute.urls', namespace='institute')),
    url(r'^library/',
        include('apiweb.apps.library.urls', namespace='library')),
    url(r'^research/',
        include('apiweb.apps.research.urls', namespace='research')),
    url(r'^publiek/',
        include('apiweb.apps.publiek.urls', namespace='publiek')),
    url(r'^jobs/',
        include('apiweb.apps.jobs.urls', namespace='jobs')),
    url(r'^apo/',
        include('apiweb.apps.apo.urls', namespace='apo')),
    url(r'^internal/account/',
        include('apiweb.apps.internal.account_urls', namespace='account')),
    url(r'^internal/staffmeetings/',
        include('apiweb.apps.staffmeetings.urls', namespace='staffmeetings')),
    url(r'^internal/agenda/',
        include('apiweb.apps.agenda.urls', namespace='agenda')),
    url(r'^internal/apogee/',
        include('apiweb.apps.apogee.urls', namespace='apogee')),
    url(r'^internal/wiki/',
        include('apiweb.apps.wiki.urls', namespace='wiki')),
    url(r'^internal/',
        include('apiweb.apps.internal.urls', namespace='internal')),
    url(r'^wiki/',
        include('apiweb.apps.wiki.viewonly_urls', namespace='wiki2')),
    url(r'^sitemap/', view=SitemapView.as_view(),
        name='sitemap'),
    url(r'^sitemap\.xml$',
        django.contrib.sitemaps.views.sitemap,
        {'sitemaps': sitemaps}),
    url(r'^search/',
        include('apiweb.apps.search.urls', namespace='search')),
    url(r'^about/$',
        view=AboutView.as_view(), name='about'),
    url(r'^24/7/$',
        view=TwentyFourSevenView.as_view(), name='247'),
    url(r'^old/',
        include('apiweb.apps.old.urls', namespace='old')),

    # redirects
    url(r'^scatter/(?P<arguments>.*)$',
        view=ScatterView.as_view(),
        name='scatter'),
    url(r'^home2.html$',
        view=HomeView.as_view(),
        name='home2'),
    url(r'^home.html$',
        view=HomeView.as_view(),
        name='home'),

    # base URL
    url(r'^$',
        MainView.as_view(),
        name='home-page'),
]

apiweb/apps/wiki/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import url
from .views import IndexView, AllView, WikiPageView
from .views import WikiCreateView, WikiEditView, WikiDeleteView

handler500 = 'apiweb.apps.main.errorview.server_error'

urlpatterns = [
    url(r'^view/(?P<name>[-\w]+)/$',
        view=WikiPageView.as_view(),
        name='view'),
    url(r'^edit/(?P<name>[-\w]+)/$',
        view=WikiEditView.as_view(),
        name='edit'),
    url(r'^delete/(?P<name>[-\w]+)/$',
        view=WikiDeleteView.as_view(),
        name='delete'),
    url(r'^create/$',
        view=WikiCreateView.as_view(),
        name='create'),
    url(r'^all/$',
        view=AllView.as_view(),
        name='all'),
    url(r'^$',
        view=IndexView.as_view(),
        name='index'),
]

apiweb/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import include, url
from django.conf import settings
import django.views.static
import sys


handler500 = 'apiweb.apps.main.errorview.server_error'


# Hack to enable the development server to find the media files,
# while keeping those files in the same place as the rest of the
# development
if 'runserver' in sys.argv:
    urlpatterns = [
        # special URLs
        url(r'^media/uploads/staff_meetings/',
            include('apiweb.apps.staffmeetings.media_urls')),
        url(r'^media/(?P<path>.*)$',
            django.views.static.serve,
            {'document_root': settings.MEDIA_ROOT}),
        url(r'^(?P<path>robots.txt)$',
            django.views.static.serve,
            {'document_root': settings.MEDIA_ROOT}),

        # normal URLs
        url(r'^', include('apiweb.apps.urls')),
    ]
else:
    urlpatterns = [url(r'^', include('apiweb.apps.urls'))]

apiweb/apps/wiki/models.py
from __future__ import unicode_literals, absolute_import, division

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from django.utils.encoding import python_2_unicode_compatible
import markdown
from .managers import WikiManager


@python_2_unicode_compatible
class WikiPage(models.Model):
    # Note: since we're storing the wiki in a separate database,
    # we can't use foreign keys, and created_author and
    # modification_author have to be Charfields instead of ForeignKeys
    name = models.CharField(_('URL name'), max_length=256, blank=False)
    text = models.TextField(_('text'), blank=True)
    html = models.TextField(_('actual HTML'), blank=True, editable=False)
    creation_date = models.DateTimeField(_('date created'),
                                         auto_now_add=True, editable=False)
    creation_author = models.CharField(_('created by'), max_length=160,
                                       blank=True, editable=False)
    modification_date = models.DateTimeField(_('date last modified'),
                                             editable=False, blank=True,
                                             null=True)
    modification_author = models.CharField(_('last modified by'),
                                           max_length=160, blank=True,
                                           editable=False)
    visits = models.IntegerField(_('number of visits'), default=0,
                                 editable=False)
    is_category_page = models.BooleanField(_('page is a category page'),
                                           default=False)
    is_visible = models.BooleanField(_('page is visible'), default=True)

    objects = models.Manager()
    visible = WikiManager()

    class Meta:
        verbose_name = _('wiki page')
        verbose_name_plural = _('wiki pages')

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        self.name = slugify(self.name)
        self.html = markdown.markdown(
            self.text, ['footnotes', 'tables', 'def_list', 'headerid'],
            safe_mode="escape")
        super(WikiPage, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('wiki:view', kwargs={'name': self.name})

    def get_absolute_url2(self):
        return reverse('wiki2:view2', kwargs={'name': self.name})

apiweb/apps/wiki/forms.py
from __future__ import unicode_literals, absolute_import, division

from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import WikiPage


class WikiPageForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(
        attrs={'cols': 70, 'rows': 40, 'autofocus': 'autofocus'}))

    class Meta:
        model = WikiPage
        fields = ['text']


class WikiPageCreateForm(forms.Form):
    name = forms.SlugField(label=_('Page name'), max_length=256,
                           widget=forms.TextInput(
                               attrs={'autofocus': 'autofocus'}))
    is_category_page = forms.BooleanField(label=_('Page is a category page'),
                                          required=False)

apiweb/apps/wiki/views.py
from __future__ import unicode_literals, absolute_import, division

from django.contrib.auth.decorators import login_required
from ...decorators import ipallowed_or_403
from django.utils.decorators import method_decorator
from django.template.defaultfilters import slugify
from django.views.generic import View, TemplateView, DetailView
from django.views.generic import FormView, UpdateView, DeleteView, RedirectView
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from datetime import datetime
from .models import WikiPage
from .forms import WikiPageForm, WikiPageCreateForm


class SecureView(View):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SecureView, self).dispatch(*args, **kwargs)


class IndexView(RedirectView, SecureView):
    permanent = False

    def get_redirect_url(self, **kwargs):
        return reverse('wiki:view', kwargs={'name': 'main-wikipage'})


class WikiPageView(DetailView):
    template_name = 'wiki/view.html'
    context_object_name = 'page'

    def get_object(self):
        object = get_object_or_404(WikiPage.visible, name=self.name)
        # Record another visit of this view
        object.visits += 1
        object.save()
        return object

#    def get_context_data(self, **kwargs):
#        context = super(WikiPageView, self).get_context_data(**kwargs)
#        context['page'] = self.page
#        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        name = kwargs.get('name', None)
        self.name = slugify(name)
        return super(WikiPageView, self).dispatch(*args, **kwargs)


class WikiEditView(UpdateView):
    """Update an old entry."""

    form_class = WikiPageForm
    template_name = 'wiki/edit.html'
    context_object_name = 'page'

    def get_object(self):
        object = get_object_or_404(WikiPage.visible, name=self.name)
        if self.request.user.username != "khouri" and \
           self.name == "api-meerkamp":
            raise Http404()
        return object

    def get_success_url(self):
        return reverse('wiki:edit', kwargs={'name': self.name})

    def form_valid(self, form):
        form.instance.modification_author = self.request.user.person.full_name
        form.instance.modification_date = datetime.now()
        return super(WikiEditView, self).form_valid(form)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        name = kwargs.get('name', None)
        self.name = slugify(name)
        return super(WikiEditView, self).dispatch(*args, **kwargs)


class WikiCreateView(FormView, SecureView):
    """Create an new entry."""

    form_class = WikiPageCreateForm
    template_name = 'wiki/create.html'

    def get_success_url(self):
        return reverse('wiki:edit', kwargs={'name': self.name})

    def form_valid(self, form):
        self.name = slugify(form.cleaned_data['name'])
        page, created = WikiPage.objects.get_or_create(name=self.name)
        page.is_category_page = form.cleaned_data['is_category_page']
        page.is_visible = True # in case page was previously deleted
        if created:
            page.creation_author = self.request.user.person.full_name
            page.modification_date = datetime.now()
        page.save()
        return HttpResponseRedirect(self.get_success_url())


class WikiDeleteView(DeleteView):
    """Delete an old entry."""

    form_class = WikiPageForm
    template_name = 'wiki/delete.html'
    context_object_name = 'page'

    def get_object(self):
        object = get_object_or_404(WikiPage.visible, name=self.name)
        if self.request.user != "khouri" and self.name == "api-meerkamp":
            raise Http404()
        return object

    def get_success_url(self):
        return reverse('wiki:view', kwargs={'name': 'main-wikipage'})

    def form_valid(self, form):
        page = self.object
        page.is_visible = False
        page.creation_author = self.request.user.person.full_name
        page.modification_date = datetime.now()
        page.save()
        return HttpResponseRedirect(self.get_success_url())

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        name = kwargs.get('name', None)
        self.name = slugify(name)
        return super(WikiDeleteView, self).dispatch(*args, **kwargs)


class AllView(TemplateView, SecureView):
    template_name = 'wiki/all.html'

    def get_context_data(self, **kwargs):
        context = super(AllView, self).get_context_data(**kwargs)
        context['category_pages'] = WikiPage.visible.filter(
            is_category_page=True).order_by('name')
        context['normal_pages'] = WikiPage.visible.filter(
            is_category_page=False).order_by('name')
        return context


class IPSecureView(View):

    @method_decorator(ipallowed_or_403)
    def dispatch(self, *args, **kwargs):
        return super(IPSecureView, self).dispatch(*args, **kwargs)


class Index2View(RedirectView, IPSecureView):
    permanent = False

    def get_redirect_url(self, **kwargs):
        return reverse('wiki2:view2', kwargs={'name': 'main-wikipage'})


class WikiPage2View(DetailView):
    template_name = 'wiki/view2.html'
    context_object_name = 'page'

    def get_object(self):
        object = get_object_or_404(WikiPage.visible, name=self.name)
        return object

#    def get_context_data(self, **kwargs):
#        context = super(WikiPage2View, self).get_context_data(**kwargs)
#        context['page'] = self.page
#        return context

    @method_decorator(ipallowed_or_403)
    def dispatch(self, *args, **kwargs):
        name = kwargs.get('name', None)
        self.name = slugify(name)
        return super(WikiPage2View, self).dispatch(*args, **kwargs)


class All2View(TemplateView, IPSecureView):
    template_name = 'wiki/all2.html'

    def get_context_data(self, **kwargs):
        context = super(All2View, self).get_context_data(**kwargs)
        context['category_pages'] = WikiPage.visible.filter(
            is_category_page=True).order_by('name')
        context['normal_pages'] = WikiPage.visible.filter(
            is_category_page=False).order_by('name')
        return context

apiweb/apps/wiki/templates/wiki/all.html
{% extends "wiki/base.html" %}
{% block title %}API wiki - List of all pages{% endblock title %}

{% block contents %}
<h1>List of all pages</h1>

{% if category_pages %}
<h2>Category pages</h2>
<ul>
{% for page in category_pages %}
  <li> <a href="{{ page.get_absolute_url }}">{{ page.name }}</a> </li>
{% endfor %}
</lu>
{% endif %}

{% if normal_pages %}
<h2>Other pages</h2>
<ul>
{% for page in normal_pages %}
  <li> <a href="{{ page.get_absolute_url }}">{{ page.name }}</a> </li>
{% endfor %}
</lu>
{% endif %}
{% endblock contents %}

apiweb/apps/wiki/templates/wiki/all2.html
{% extends "wiki/base2.html" %}
{% block title %}API wiki - List of all pages{% endblock title %}

{% block contents %}
<h1>List of all pages</h1>

{% if category_pages %}
<h2>Category pages</h2>
<ul>
{% for page in category_pages %}
  <li> <a href="{{ page.get_absolute_url2 }}">{{ page.name }}</a> </li>
{% endfor %}
</lu>
{% endif %}

{% if normal_pages %}
<h2>Other pages</h2>
<ul>
{% for page in normal_pages %}
  <li> <a href="{{ page.get_absolute_url2 }}">{{ page.name }}</a> </li>
{% endfor %}
</lu>
{% endif %}
{% endblock contents %}

apiweb/apps/wiki/templates/wiki/base.html
{% extends "base.html" %}
{% block stylesheets %}<base href="http://{{ location.site }}/internal/wiki/view/" />{{ block.super }}<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}wiki/css/wiki.css" />{% endblock stylesheets %}
{% block banner %}<div id="banner"><h1>API Wiki</h1></div>{% endblock banner %}
{% block breadcrumbs %}{{ block.super }} &#187; <a href="{% url 'wiki:index' %}">Wiki</a>{% endblock breadcrumbs %}
{% block sidemenu %}
{% include "wiki/sidemenu.html" %}
{% endblock sidemenu %}

apiweb/apps/wiki/templates/wiki/base2.html
{% extends "base.html" %}
{% block stylesheets %}<base href="http://{{ location.site }}/wiki/view/" />{{ block.super }}<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}wiki/css/wiki.css" />{% endblock stylesheets %}
{% block banner %}<div id="banner"><h1>API Wiki</h1></div>{% endblock banner %}
{% block breadcrumbs %}{{ block.super }} &#187; <a href="{% url 'wiki2:index2' %}">Wiki</a>{% endblock breadcrumbs %}
{% block sidemenu %}
{% include "wiki/sidemenu2.html" %}
{% endblock sidemenu %}

apiweb/apps/wiki/templates/wiki/create.html
{% extends "wiki/base.html" %}
{% block title %}API wiki - create a new page{% endblock title %}

{% block contents %}
<form method="POST" action="{% url 'wiki:create' %}"> {% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Create" />
{% endblock contents %}

apiweb/apps/wiki/templates/wiki/delete.html
{% extends "wiki/base.html" %}
{% block title %}{{ page.name }}{% endblock title %}

{% block contents %}


<form method="POST" action="{% url 'wiki:delete' name=page.name %}"> {% csrf_token %}
<em>{{ page.name }}: delete this page?</em>
<br />
<input type="submit" name="result" value="Delete" />
<input type="button" value="Cancel" onclick="window.location.href='{% url 'wiki:view' name=page.name %}'" />
</form>

<hr />

{{ page.html|safe }}

{% endblock contents %}

apiweb/apps/wiki/templates/wiki/edit.html
{% extends "wiki/base.html" %}
{% block title %}{{ page.name }}{% endblock title %}

{% block contents %}

<h1>Editing page <em>{{ page.name }}</em></h1>

<div class="preview">
{{ page.html|safe }}
</div>

<div class="edit">
<form method="post" action=""> {% csrf_token %}
<input type="submit" value="Save" /> <a href="{% url 'wiki:view' name=page.name %}">To normal page view </a>
{{ form.text }}
<input type="submit" value="Save" /> <a href="{% url 'wiki:view' name=page.name %}">To normal page view</a>
</form>
</div>

{% endblock contents %}

apiweb/apps/wiki/templates/wiki/sidemenu.html
{% url 'internal:index' as internal_index %}
{% url 'internal:addresses' as internal_addresses %}
{% url 'internal:addresses-phonelist' as internal_addresses_phonelist %}
{% url 'account:login' as account_login %}
{% url 'account:logout' as account_logout %}
{% url 'account:password-change' as account_password_change %}
{% url 'internal:edit-profile' as internal_edit_profile  %}
{% url 'internal:create-profile' as internal_create_profile  %}
{% url 'internal:show-profile' as internal_show_profile  %}
{% url 'internal:observatory' as internal_observatory  %}
{% url 'staffmeetings:index' as staffmeetings_index %}
{% url 'agenda:index' as agenda_index %}
{% url 'apogee:index' as apogee_index %}
{% url 'library:index' as library_index %}
{% url 'internal:logo' as internal_logo %}
{% url 'wiki:view' name="main-wikipage" as wiki_main %}
{% url 'wiki:create' as wiki_create %}
{% url 'wiki:all' as wiki_allpages %}
{% url 'wiki:view' name="help-editing-wikipage" as wiki_editing %}

<ul>
  <li> <a {% ifequal request.path internal_index %}class="active" {% endifequal %} href="{{ internal_index }}">Internal</a>
    <ul>
      <li> <a {% ifequal request.path account_login %}class="active" {% endifequal %} href="{{ account_login }}">Login</a> </li>
      <li> <a {% ifequal request.path internal_logout %}class="active" {% endifequal %} href="{{ account_logout }}">Logout</a> </li>
      <li> <a {% ifequal request.path internal_password_change %}class="active" {% endifequal %} href="{{ account_password_change }}">Change Password</a> </li>
      <li> <a {% ifequal request.path internal_edit_profile %}class="active" {% endifequal %}{% ifequal request.path internal_create_profile %}class="active" {% endifequal %} href="{{internal_edit_profile}}">Edit Profile</a> </li>
      <li> <a {% ifequal request.path internal_show_profile %}class="active" {% endifequal %} href="{{internal_show_profile}}">Show Profile</a> </li>
      <li> <a {% ifequal request.path internal_addresses %}class="active" {% endifequal %} href="{{ internal_addresses }}">Address list</a> </li>
      <li> <a {% ifequal request.path library_index %}class="active" {% endifequal %}href="{{ library_index }}">Library</a> </li>
      <li> <a {% ifequal request.path internal_observatory %}class="active" {% endifequal %}href="{{ internal_observatory }}">Observatory (apo)</a> </li>
      <li> <a {% ifequal request.path apogee_index %}class="active" {% endifequal %}href="{{ apogee_index }}">APO Agenda</a> </li>
      <li> <a {% ifequal request.path staffmeetings_index %}class="active" {% endifequal %}href="{{ staffmeetings_index }}">API staff meetings</a> </li>
      <li> <a {% ifequal request.path agenda_index %}class="active" {% endifequal %}href="{{ agenda_index }}">API Agenda</a> </li>
      <li> <a {% ifequal request.path internal_logo %}class="active" {% endifequal %}href="{{ internal_logo }}">API logo</a> </li>
      <li> <a {% ifequal request.path wiki_main %}class="active" {% endifequal %}href="{{ wiki_main }}">Wiki</a>
        <ul>
          <li> <a {% ifequal request.path wiki_allpages %}class="active" {% endifequal %}href="{{ wiki_allpages }}">List of all pages</a> </li>
          <li> <a {% ifequal request.path wiki_create %}class="active" {% endifequal %}href="{% url 'wiki:create' %}">Create a new page</a> </li>
          <li> <a {% ifequal request.path wiki_editing %}class="active" {% endifequal %}href="{{ wiki_editing }}">Help on editing</a> </li>
        </ul>
      </li>
    </ul>
  </li>
</ul>

apiweb/apps/wiki/templates/wiki/sidemenu2.html
{% url 'wiki2:view2' name="main-wikipage" as wiki_main %}
{% url 'wiki2:all2' as wiki_allpages %}
{% url 'wiki2:view2' name="help-editing-wikipage" as wiki_editing %}

<ul>
  <li>  <a {% ifequal request.path wiki_main %}class="active" {% endifequal %}href="{{ wiki_main }}">Wiki</a>
    <ul>
      <li> <a {% ifequal request.path wiki_allpages %}class="active" {% endifequal %}href="{{ wiki_allpages }}">List of all pages</a> </li>
      <li> <a {% ifequal request.path wiki_editing %}class="active" {% endifequal %}href="{{ wiki_editing }}">Help on editing</a> </li>
    </ul>
  </li>
</ul>

apiweb/apps/wiki/templates/wiki/view.html
{% extends "wiki/base.html" %}
{% block title %}API wiki - {{ page.name }}{% endblock title %}

{% block contents %}
{{ page.html|safe }}
<hr>
<p class="note right">
<a href="/internal/wiki/edit/{{ page.name }}">Edit page</a> &nbsp; | &nbsp;
<a href="/internal/wiki/delete/{{ page.name }}">Delete page</a>
</p>
{% endblock contents %}

apiweb/apps/wiki/templates/wiki/view2.html
{% extends "wiki/base2.html" %}
{% block title %}API wiki - {{ page.name }}{% endblock title %}

{% block contents %}
<div class="note right" style="position: static; top -2em;">You're reading the read-only version of the API wiki. <a href="{% url 'wiki:index' %}">Log in</a> if you'd like to edit.</div>
{{ page.html|safe }}
{% endblock contents %}