apiweb/apps/apogee/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import url
from .views import IndexView, MonthView, WeekView, EntryDetailView
from .views import EntryCreateView, EntryUpdateView, EntryDeleteView
from ..main.views import DetailRedirectView
from .models import Entry


handler500 = 'apiweb.apps.main.errorview.server_error'

urlpatterns = [
    url(r'^detail/(?P<pk>\d+)/(?P<slug>[-\w]+)/$',
        view=EntryDetailView.as_view(),
        name='entry-detail'),
    url(r'^detail/(?P<slug>[-\w]+)/$',
        view=DetailRedirectView.as_view(model=Entry),
        name='entry-redirect'),
    url(r'^update/(?P<pk>\d+)/(?P<slug>[-\w]+)/$',
        view=EntryUpdateView.as_view(),
        name='entry-update'),
    url(r'^delete/(?P<pk>\d+)/(?P<slug>[-\w]+)/$',
        view=EntryDeleteView.as_view(),
        name='entry-delete'),
    url(r'^create/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$',
        view=EntryCreateView.as_view(),
        name='entry-create'),
    url(r'^month/(?P<year>\d+)/(?P<month>\d+)/(?P<change>(prev|next))/$',
        view=MonthView.as_view(),
        name='month'),
    url(r'^month/(?P<year>\d+)/(?P<month>\d+)/$',
        view=MonthView.as_view(),
        name='month'),
    url(r'^month/$',
        view=MonthView.as_view(),
        name='month'),
    url(r'^week/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/'
        '(?P<change>(prev|next))/$',
        view=WeekView.as_view(),
        name='week'),
    url(r'^week/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$',
        view=WeekView.as_view(),
        name='week'),
    url(r'^week/$',
        view=WeekView.as_view(),
        name='week'),
    url(r'^(?P<year>\d+)/$',
        view=IndexView.as_view(),
        name='index'),
    url(r'^$',
        view=IndexView.as_view(),
        name='index'),
]

apiweb/apps/internal/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import url
from .views import LogoView, IndexView, ObservatoryView, AdressesView
from .views import ShowProfileView, CreateProfileView, EditProfileView
from .phonelist import TelephonelistView

handler500 = 'apiweb.apps.main.errorview.server_error'

urlpatterns = [
    url(r'^create/$',
        view=CreateProfileView.as_view(),
        name='create-profile'),
    url(r'^edit/$',
        view=EditProfileView.as_view(),
        name='edit-profile'),
    url(r'^show/$',
        view=ShowProfileView.as_view(),
        name='show-profile'),
    url(r'^logo/$',
        view=LogoView.as_view(),
        name='logo'),
    url(r'^observatory/$',
        view=ObservatoryView.as_view(),
        name='observatory'),
    url(r'^addresses/phonelist/$',
        view=TelephonelistView.as_view(),

        name='addresses-phonelist'),
    url(r'^addresses/$',
        view=AdressesView.as_view(),
        name='addresses'),
    url(r'^show/$',
        view=ShowProfileView.as_view(),
        name='show-profile'),
    url(r'^edit/$',
        view=EditProfileView.as_view(),
        name='edit-profile'),
    url(r'^create/$',
        view=CreateProfileView.as_view(),
        name='create-profile'),
    url(r'^$',
        view=IndexView.as_view(),
        name='index'),
]

apiweb/apps/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import include, url
from django.contrib import admin
import django.contrib.sitemaps.views
from .main.sitemap import sitemaps
from .main.views import MainView, HomeView, ScatterView, LowercaseView
from .main.views import SitemapView, AboutView, TwentyFourSevenView
import filebrowser.sites


admin.autodiscover()

urlpatterns = [
    url(r'^.*[A-Z]+.*$',
        view=LowercaseView.as_view(),
        name='redirect-uppercase'),

    url(r'^media/uploads/staff_meetings/',
        include('apiweb.apps.staffmeetings.media_urls')),

    url(r'^admin/filebrowser/',
        include(filebrowser.sites.site.urls)),

    #url(r'^admin/filebrowser/',
    #    include('filebrowser.urls', namespace='filebrowser')),
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # deprecated url(r'^admin/(.*)', admin.site.root, name='admin-root'),
    # to use new setup in templates, use {% url admin:index %}
    url(r'^admin/',
        include(admin.site.urls)),

    url(r'^news/',
        include('apiweb.apps.news.urls', namespace='news')),
    url(r'^people/',
        include('apiweb.apps.people.urls', namespace='people')),
    url(r'^education/',
        include('apiweb.apps.education.urls', namespace='education')),
    url(r'^institute/',
        include('apiweb.apps.institute.urls', namespace='institute')),
    url(r'^library/',
        include('apiweb.apps.library.urls', namespace='library')),
    url(r'^research/',
        include('apiweb.apps.research.urls', namespace='research')),
    url(r'^publiek/',
        include('apiweb.apps.publiek.urls', namespace='publiek')),
    url(r'^jobs/',
        include('apiweb.apps.jobs.urls', namespace='jobs')),
    url(r'^apo/',
        include('apiweb.apps.apo.urls', namespace='apo')),
    url(r'^internal/account/',
        include('apiweb.apps.internal.account_urls', namespace='account')),
    url(r'^internal/staffmeetings/',
        include('apiweb.apps.staffmeetings.urls', namespace='staffmeetings')),
    url(r'^internal/agenda/',
        include('apiweb.apps.agenda.urls', namespace='agenda')),
    url(r'^internal/apogee/',
        include('apiweb.apps.apogee.urls', namespace='apogee')),
    url(r'^internal/wiki/',
        include('apiweb.apps.wiki.urls', namespace='wiki')),
    url(r'^internal/',
        include('apiweb.apps.internal.urls', namespace='internal')),
    url(r'^wiki/',
        include('apiweb.apps.wiki.viewonly_urls', namespace='wiki2')),
    url(r'^sitemap/', view=SitemapView.as_view(),
        name='sitemap'),
    url(r'^sitemap\.xml$',
        django.contrib.sitemaps.views.sitemap,
        {'sitemaps': sitemaps}),
    url(r'^search/',
        include('apiweb.apps.search.urls', namespace='search')),
    url(r'^about/$',
        view=AboutView.as_view(), name='about'),
    url(r'^24/7/$',
        view=TwentyFourSevenView.as_view(), name='247'),
    url(r'^old/',
        include('apiweb.apps.old.urls', namespace='old')),

    # redirects
    url(r'^scatter/(?P<arguments>.*)$',
        view=ScatterView.as_view(),
        name='scatter'),
    url(r'^home2.html$',
        view=HomeView.as_view(),
        name='home2'),
    url(r'^home.html$',
        view=HomeView.as_view(),
        name='home'),

    # base URL
    url(r'^$',
        MainView.as_view(),
        name='home-page'),
]

apiweb/apps/wiki/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import url
from .views import IndexView, AllView, WikiPageView
from .views import WikiCreateView, WikiEditView, WikiDeleteView

handler500 = 'apiweb.apps.main.errorview.server_error'

urlpatterns = [
    url(r'^view/(?P<name>[-\w]+)/$',
        view=WikiPageView.as_view(),
        name='view'),
    url(r'^edit/(?P<name>[-\w]+)/$',
        view=WikiEditView.as_view(),
        name='edit'),
    url(r'^delete/(?P<name>[-\w]+)/$',
        view=WikiDeleteView.as_view(),
        name='delete'),
    url(r'^create/$',
        view=WikiCreateView.as_view(),
        name='create'),
    url(r'^all/$',
        view=AllView.as_view(),
        name='all'),
    url(r'^$',
        view=IndexView.as_view(),
        name='index'),
]

apiweb/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import include, url
from django.conf import settings
import django.views.static
import sys


handler500 = 'apiweb.apps.main.errorview.server_error'


# Hack to enable the development server to find the media files,
# while keeping those files in the same place as the rest of the
# development
if 'runserver' in sys.argv:
    urlpatterns = [
        # special URLs
        url(r'^media/uploads/staff_meetings/',
            include('apiweb.apps.staffmeetings.media_urls')),
        url(r'^media/(?P<path>.*)$',
            django.views.static.serve,
            {'document_root': settings.MEDIA_ROOT}),
        url(r'^(?P<path>robots.txt)$',
            django.views.static.serve,
            {'document_root': settings.MEDIA_ROOT}),

        # normal URLs
        url(r'^', include('apiweb.apps.urls')),
    ]
else:
    urlpatterns = [url(r'^', include('apiweb.apps.urls'))]

apiweb/apps/apogee/models.py
from __future__ import unicode_literals, absolute_import, division

from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.core.urlresolvers import reverse
import markdown


@python_2_unicode_compatible
class Entry(models.Model):
    """Represents a entry in the API Agenda."""

    DOME_CHOICES = (
        (1, 'Stellar Dome'),
        (2, 'Solar Dome'),
        (3, 'Observation Platform'),
    )

    title = models.CharField(_('title'), max_length=120, default="Practicum")
    dome = models.PositiveSmallIntegerField(_('dome'), choices=DOME_CHOICES,
                                            default=1)
    body = models.TextField(_('text'), max_length=10000, blank=True, default="")
    body_html = models.TextField(_('actual html body'), max_length=16000,
                                 blank=True, editable=False, default="")
#   date = models.DateField(_('date of observing'), default=datetime.date.today)
    date = models.DateField(_('date of observing'))
    date_end = models.DateField(
        _('end date of observing'), blank=True, null=True,
        help_text=_("End date of the observations, if different from the "
                    "start date"))
    creator = models.ForeignKey(User, related_name='apo_creator')
    slug = models.SlugField(_('slug'), max_length=500, blank=False,
                            editable=False, unique=False)


    def save(self, *args, **kwargs):
        self.slug = '{}_{}-{}-{}_{}'.format(self.dome, self.date.year,
                                            self.date.month, self.date.day,
                                            slugify(self.title))
        self.body_html = markdown.markdown(
            self.body,
            ['footnotes', 'tables', 'def_list', 'headerid'],
            safe_mode="escape")
        super(Entry, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "entry"
        verbose_name_plural = "entries"

    def __str__(self):
        if self.title:
            return str(self.creator) + " - " + self.title
        else:
            return str(self.creator)

    def get_absolute_url(self):
        return reverse('apogee:entry-detail',
                       kwargs={'pk': self.pk, 'slug': self.slug})

apiweb/apps/apogee/forms.py
from __future__ import unicode_literals, absolute_import, division

from django import forms
from .models import Entry

class EntryAdminForm(forms.ModelForm):

    class Meta:
        model = Entry
        fields = '__all__'

    def clean(self):
        cleaned_data = self.cleaned_data
        date = cleaned_data.get("date")
        date_end = cleaned_data.get("date_end")

        if date and date_end:
            # Only do something if both fields are valid so far.
            if date > date_end:
                raise forms.ValidationError(
                    "The end date of an event "
                    "should be later than the date of the event.")

        # Always return the full collection of cleaned data.
        return cleaned_data


#class EntryForm(EntryAdminForm):
class EntryForm(forms.ModelForm):

    class Meta:
        model = Entry
        exclude = ('creator',)

apiweb/apps/apogee/templates/apogee/base.html
{% extends "base.html" %}
{% block stylesheets %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}apogee/css/apogee.css" />{% endblock stylesheets %}
{% block banner %}<div id="banner"><h1>APO booking calendar</h1></div>{% endblock banner %}
{% block breadcrumbs %}
{{ block.super }} &#187; <a href="{% url 'apogee:index' %}">Calendar</a>
{% endblock breadcrumbs %}
{% block sidemenu %}
{% include "apogee/sidemenu.html" %}
{% endblock sidemenu %}

apiweb/apps/apogee/templates/apogee/entry_create.html
{% extends "apogee/base.html" %}


{% block contents %}
<h1>APO calendar -- Creating my Entry</h1>

<style type="text/css">
    .main { border: 3px solid #eee; padding: 8px; }
    .entry { border: 3px solid #eee; padding: 10px; width: 400px; margin: 9px;}
    .del { float: right; }
     h4 { text-align: left; margin-left: 50px; }
</style>


<div class="main">


{% if form.non_field_errors %}
<font color="red">Sorry there are corrections needed in your form below:</font>
   {{ form.non_field_errors }}
{% endif %}

<br />

<form action="{% url 'apogee:entry-create' year month day  %}" method="POST"> {% csrf_token %}

<table>
{% if form.title.errors %}
<tr><th>{{ form.title.label_tag }}:</th><td>{{ form.title.errors }}</td><th></th></tr>
{% endif %}
<tr><th>{{ form.title.label_tag }} </th><td>{{ form.title }}</td><th></th></tr>

{% if form.dome.errors %}
<tr><th>{{ form.dome.label_tag }}:</th><td>{{ form.dome.errors }}</td><th></th></tr>
{% endif %}
<tr><th>{{ form.dome.label_tag }} </th><td>{{ form.dome }} </td><th>(stellar, solar or observation platform)</th> </tr>

{% if form.date.errors %}
<tr><th>{{ form.date.label_tag }}:</th><td>{{ form.date.errors }}</td><th></th></tr>
{% endif %}
<tr><th>{{ form.date.label_tag }} </th><td>{{ form.date }} </td><th>(YYYY-MM-DD)</th></tr>

{% if form.date_end.errors %}
<tr><th>{{ form.date_end.label_tag }}:</th><td>{{ form.date_end.errors }}</td><th></th></tr>
{% endif %}
<tr><th>{{ form.date_end.label_tag }} </th><td>{{ form.date_end }} </td><th>(if different from date)
</th></tr>
</table>

<p>

</p>

<table>
{% if form.body.errors %}
<tr><th>{{ form.body.label_tag }}:</th><td>{{ form.body.errors }}</td><th></th></tr>
{% endif %}
<tr><th>{{ form.body.label_tag }} </th><td>{{ form.body }} </td><th>(same as editing an api wiki page)</th></tr>
</table>

<input type="submit" name="result" value="Save" />
<input type="button" value="Cancel" onclick="window.location.href='{% url 'apogee:month' year month %}'" />
</form>

</div>


{% endblock contents %}

apiweb/apps/apogee/templates/apogee/entry_delete.html
{% extends "apogee/base.html" %}
{% block title %}APO Agenda - {{ object.title }}{% endblock title %}

{% block contents %}

<form method="POST" action="{% url 'apogee:entry-delete' pk=object.pk slug=object.slug %}">
{% csrf_token %}
<em>{{ object.title }}</em>

<p>
Delete this entry? <br />
<input type="submit" name="result" value="Delete" />
<input type="submit" name="result" value="Cancel" />
</p>
</form>

<hr />

<p>

</p>


{% if object.is_public %}
<p class="warning right">This item is visible to the public</p>
{% endif %}

<h1>{{ object.title }}</h1>

<p>
{{ object.date|date:"j F Y" }}
{% if object.enddate %} - {{ object.enddate|date:"j F Y" }} {% endif %}
<br />
This agenda item has been created by {{ object.creator.get_full_name }}.
<hr>
</p>

<p>
{{ object.body_html|safe }}
</p>

{% endblock contents %}

apiweb/apps/apogee/templates/apogee/entry_detail.html
{% extends "apogee/base.html" %}
{% block title %}APO Agenda - {{ object.title }}{% endblock title %}

{% block breadcrumbs %}
{{ block.super }} &#187; <a href="{% url 'apogee:index' %}">APO Agenda</a> &#187; {{ object.title }}
{% endblock breadcrumbs %}

{% block contents %}

<h1>{{ object.title }}</h1>

<p>
{{ object.date|date:"j F Y" }}
{% if object.date_end %} - {{ object.date_end|date:"j F Y" }} {% endif %}
<br />
This agenda item has been created by {{ object.creator.get_full_name }}.
<hr>
</p>

<p>
{{ object.body_html|safe }}
</p>


{% ifequal object.creator request.user %}
<hr>
<p class="note right">
<a href="{% url 'apogee:entry-update' object.pk object.slug %}">Update Entry</a> &nbsp; | &nbsp;
<a href="{% url 'apogee:entry-delete' object.pk object.slug %}">Delete Entry</a>
</p>
{% endifequal %}


{% endblock contents %}

apiweb/apps/apogee/templates/apogee/entry_update.html
{% extends "apogee/base.html" %}


{% block contents %}
<h1>APO calendar -- Update my Entry</h1>

<style type="text/css">
    .main { border: 3px solid #eee; padding: 8px; }
    .entry { border: 3px solid #eee; padding: 10px; width: 400px; margin: 9px;}
    .del { float: right; }
     h4 { text-align: left; margin-left: 50px; }
</style>


<div class="main">


{% if form.non_field_errors %}
<font color="red">Sorry there are corrections needed in your form below:</font>
   {{ form.non_field_errors }}
{% endif %}

<br />

<form action="{% url 'apogee:entry-update' object.pk object.slug %}" method="POST"> {% csrf_token %}

<table>
{% if form.title.errors %}
<tr><th>{{ form.title.label_tag }}:</th><td>{{ form.title.errors }}</td><th></th></tr>
{% endif %}
<tr><th>{{ form.title.label_tag }} </th><td>{{ form.title }}</td><th></th></tr>

{% if form.dome.errors %}
<tr><th>{{ form.dome.label_tag }}:</th><td>{{ form.dome.errors }}</td><th></th></tr>
{% endif %}
<tr><th>{{ form.dome.label_tag }} </th><td>{{ form.dome }} </td><th>(stellar, solar or observation platform)</th> </tr>

{% if form.date.errors %}
<tr><th>{{ form.date.label_tag }}:</th><td>{{ form.date.errors }}</td><th></th></tr>
{% endif %}
<tr><th>{{ form.date.label_tag }} </th><td>{{ form.date }} </td><th>(YYYY-MM-DD)</th></tr>

{% if form.date_end.errors %}
<tr><th>{{ form.date_end.label_tag }}:</th><td>{{ form.date_end.errors }}</td><th></th></tr>
{% endif %}
<tr><th>{{ form.date_end.label_tag }} </th><td>{{ form.date_end }} </td><th>(if different from date)
</th></tr>
</table>

<p>

</p>

<table>
{% if form.body.errors %}
<tr><th>{{ form.body.label_tag }}:</th><td>{{ form.body.errors }}</td><th></th></tr>
{% endif %}
<tr><th>{{ form.body.label_tag }} </th><td>{{ form.body }} </td><th>(same as editing an api wiki page)</th></tr>
</table>

<input type="submit" name="result" value="Save" />
<input type="button" value="Cancel" onclick="window.location.href='{% url 'apogee:entry-detail' object.pk object.slug %}'" />
</form>

</div>


{% endblock contents %}

apiweb/apps/apogee/templates/apogee/index.html
{% extends "apogee/base.html" %}
{% block title %}API - Internal APO agenda{% endblock title %}
{% block contents %}


<h1>APO booking calendar</h1>

<p>(made reservations can be found in the <b>bold</b> months)</p>


<a id="prev" href="{% url 'apogee:index' year|add:'-3' %}">&lt;&lt; Prev</a>
<a id="next" href="{% url 'apogee:index' year|add:'3' %}">Next &gt;&gt;</a>

{% for year, months in years %}

  <h4>{{ year }}</h4>

  <table class="year">
  <thead />
  <tr>
  {% for month in months %}
    <td class="{% if month.current %}current{% endif %}">
          {% if month.entry %}<b>{% endif %}<a href="{% url 'apogee:month' year month.n %}">{{ month.name }}</a>{% if month.entry %}</b>{% endif %}
    </td>
    {% if month.n == 6 %}</tr><tr>{% endif %}
  {% endfor %}
  </tr>
  </table>

{% endfor %}


{% endblock contents %}

apiweb/apps/apogee/templates/apogee/month.html
{% extends "apogee/base.html" %}
{% block title %}API - Internal APO agenda by month{% endblock title %}

{% block contents %}

<h1>APO calendar for this month (click on a day to add your entry)</h1>

<p>
The <font color="purple"> purple items </font> are reservations for the Stellar telescope. <br />
The <font color="green"> green items </font> are reservations for the Solar telescope. <br />
The <font color="blue"> blue items </font> are reservations for the Observation platform. <br />
</p>


<a id="prev" href= "{% url 'apogee:month' year month "prev" %}">&lt;&lt; Prev</a>
<a id="next" href= "{% url 'apogee:month' year month "next" %}">Next &gt;&gt;</a>


<h4>{{ mname }} {{ year }}</h4>

    <table class="month">
    <thead>
    <tr><th>Mon</th><th>Tue</th><th>Wed</th><th>Thu</th><th>Fri</th><th>Sat</th><th>Sun</th></tr>
    </thead>
    {% for week in month_days %}
    <tr>
       {% for day, moonimage, entries, current in week %}
           <td class="{% if day != 0 %}{% if current %}current{% endif %}{% else %}empty{% endif %}"
           {% if day != 0 %} onClick="parent.location='{% url 'apogee:entry-create' year month day %}'" onMouseOver="this.bgColor='#eee';" onMouseOut="this.bgColor='white';"{% endif %}>
           {% if day != 0 %}
              {{ day }} <img src="{{ STATIC_URL }}apogee/images/{{moonimage}}" style="height: 20px; float: right;" />
              {% for entry in entries %}
                <li><a href="{{entry.link}}" title="{{entry.tooltip}}"><font color={{entry.attr}}> {{entry.type|truncatewords:2}} </font></a></li>
              {% endfor %}
           {% endif %}
           </td>
       {% endfor %}
    </tr>
    {% endfor %}

    </table>

{% endblock contents %}

apiweb/apps/apogee/templates/apogee/sidemenu.html
{% url 'internal:index' as internal_index %}
{% url 'internal:addresses' as internal_addresses %}
{% url 'internal:addresses-phonelist' as internal_addresses_phonelist %}
{% url 'account:login' as account_login %}
{% url 'account:logout' as account_logout %}
{% url 'account:password-change' as account_password_change %}
{% url 'internal:edit-profile' as internal_edit_profile  %}
{% url 'internal:create-profile' as internal_create_profile  %}
{% url 'internal:show-profile' as internal_show_profile  %}
{% url 'internal:observatory' as internal_observatory  %}
{% url 'staffmeetings:index' as staffmeetings_index %}
{% url 'library:index' as library_index %}
{% url 'agenda:index' as agenda_index %}
{% url 'apogee:index' as apogee_index %}
{% url 'apogee:week' as apogee_week %}
{% url 'apogee:month' as apogee_month %}
{% url 'internal:logo' as internal_logo %}
{% url 'wiki:view' name="main-wikipage" as wiki_main %}

<ul>
<li> <a {% ifequal request.path internal_index %}class="active" {% endifequal %} href="{{ internal_index }}">Internal</a>
     <ul>
        <li> <a {% ifequal request.path account_login %}class="active" {% endifequal %} href="{{ account_login }}">Login</a> </li>
        <li> <a {% ifequal request.path internal_logout %}class="active" {% endifequal %} href="{{ account_logout }}">Logout</a> </li>
        <li> <a {% ifequal request.path internal_password_change %}class="active" {% endifequal %} href="{{ account_password_change }}">Change Password</a> </li>
        <li> <a {% ifequal request.path internal_edit_profile %}class="active" {% endifequal %}
                {% ifequal request.path internal_create_profile %}class="active" {% endifequal %} href="{{internal_edit_profile}}">Edit Profile</a> </li>
        <li> <a {% ifequal request.path internal_show_profile %}class="active" {% endifequal %} href="{{internal_show_profile}}">Show Profile</a> </li>
        <li> <a {% ifequal request.path internal_addresses %}class="active" {% endifequal %} href="{{ internal_addresses }}">Address list</a> </li>
        <li> <a {% ifequal request.path library_index %}class="active" {% endifequal %}href="{{ library_index }}">Library</a> </li>
        <li> <a {% ifequal request.path internal_observatory %}class="active" {% endifequal %}href="{{ internal_observatory }}">Observatory (apo)</a> </li>
        <li> <a {% ifequal request.path apogee_index %}class="active" {% endifequal %}href="{{ apogee_index }}">APO Agenda</a>
             <ul>
             <li> <a {% ifequal request.path apogee_week %}class="active"  {% endifequal %} href="{{ apogee_week }}">Current Week</a> </li>
             <li> <a {% ifequal request.path apogee_month %}class="active" {% endifequal %} href="{{ apogee_month }}">Current Month</a> </li>
             </ul>
        </li>
        <li> <a {% ifequal request.path staffmeetings_index %}class="active" {% endifequal %}href="{{ staffmeetings_index }}">API staff meetings</a> </li>
        <li> <a {% ifequal request.path agenda_index %}class="active" {% endifequal %}href="{{ agenda_index }}">API Agenda</a> </li>
        <li> <a {% ifequal request.path internal_logo %}class="active" {% endifequal %}href="{{ internal_logo }}">API logo</a> </li>
        <li> <a {% ifequal request.path wiki_main %}class="active" {% endifequal %}href="{{ wiki_main }}">Wiki</a> </li>
     </ul>
</li>
</ul>

apiweb/apps/apogee/templates/apogee/week.html
{% extends "apogee/base.html" %}
{% block title %}API - Internal APO agenda by week{% endblock title %}

{% block contents %}


<h1>APO calendar for this week (click on a day to add your entry)</h1>

<p>
The <font color="purple"> purple items </font> are reservations for the Stellar telescope. <br />
The <font color="green"> green items </font> are reservations for the Solar telescope. <br />
The <font color="blue"> blue items </font> are reservations for the Observation platform. <br />
</p>


<a id="prev" href= "{% url 'apogee:week' year month day "prev" %}">&lt;&lt; Prev</a>
<a id="next" href= "{% url 'apogee:week' year month day "next" %}">Next &gt;&gt;</a>


{% for week_day, sunset, moonimage, this_year, this_month, this_day, entries, current in week_days %}
   <h4>{{ week_day|date:"l, j F Y" }}</h4>

   <div class="weekday {% if current %}current{% endif %}"
 onClick="parent.location='{% url 'apogee:entry-create' this_year this_month this_day %}'" onMouseOver="this.style.backgroundColor='#eeeeee';" onMouseOut="this.style.backgroundColor={% if current %}'#eeeec8'{% else %}'white'{% endif %};" >
   <table>
      <tr>
      <td width=80% align="left">
      {% for entry in entries %}
           <li><a href="{{entry.link}}" title="{{entry.tooltip}}"><font color={{entry.attr}}> {{entry.type}} </font></a></li>
      {% endfor %}
      </td>
      <td width=20% align="center"> Sunset = {{sunset|time:"H:i"}}  <img src="{{ STATIC_URL }}apogee/images/{{moonimage}}" height="100" /> </td>
      </tr>
   </table>
   </div>

{% endfor %}

{% endblock contents %}