apiweb/apps/internal/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import url
from .views import LogoView, IndexView, ObservatoryView, AdressesView
from .views import ShowProfileView, CreateProfileView, EditProfileView
from .phonelist import TelephonelistView

handler500 = 'apiweb.apps.main.errorview.server_error'

urlpatterns = [
    url(r'^create/$',
        view=CreateProfileView.as_view(),
        name='create-profile'),
    url(r'^edit/$',
        view=EditProfileView.as_view(),
        name='edit-profile'),
    url(r'^show/$',
        view=ShowProfileView.as_view(),
        name='show-profile'),
    url(r'^logo/$',
        view=LogoView.as_view(),
        name='logo'),
    url(r'^observatory/$',
        view=ObservatoryView.as_view(),
        name='observatory'),
    url(r'^addresses/phonelist/$',
        view=TelephonelistView.as_view(),

        name='addresses-phonelist'),
    url(r'^addresses/$',
        view=AdressesView.as_view(),
        name='addresses'),
    url(r'^show/$',
        view=ShowProfileView.as_view(),
        name='show-profile'),
    url(r'^edit/$',
        view=EditProfileView.as_view(),
        name='edit-profile'),
    url(r'^create/$',
        view=CreateProfileView.as_view(),
        name='create-profile'),
    url(r'^$',
        view=IndexView.as_view(),
        name='index'),
]

apiweb/apps/staffmeetings/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import url
from .views import IndexView

handler500 = 'apiweb.apps.main.errorview.server_error'

urlpatterns = [
    url(r'^(?P<year>\d+)/$', view=IndexView.as_view(), name='index'),
    url(r'^$', view=IndexView.as_view(), name='index'),
]

apiweb/apps/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import include, url
from django.contrib import admin
import django.contrib.sitemaps.views
from .main.sitemap import sitemaps
from .main.views import MainView, HomeView, ScatterView, LowercaseView
from .main.views import SitemapView, AboutView, TwentyFourSevenView
import filebrowser.sites


admin.autodiscover()

urlpatterns = [
    url(r'^.*[A-Z]+.*$',
        view=LowercaseView.as_view(),
        name='redirect-uppercase'),

    url(r'^media/uploads/staff_meetings/',
        include('apiweb.apps.staffmeetings.media_urls')),

    url(r'^admin/filebrowser/',
        include(filebrowser.sites.site.urls)),

    #url(r'^admin/filebrowser/',
    #    include('filebrowser.urls', namespace='filebrowser')),
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # deprecated url(r'^admin/(.*)', admin.site.root, name='admin-root'),
    # to use new setup in templates, use {% url admin:index %}
    url(r'^admin/',
        include(admin.site.urls)),

    url(r'^news/',
        include('apiweb.apps.news.urls', namespace='news')),
    url(r'^people/',
        include('apiweb.apps.people.urls', namespace='people')),
    url(r'^education/',
        include('apiweb.apps.education.urls', namespace='education')),
    url(r'^institute/',
        include('apiweb.apps.institute.urls', namespace='institute')),
    url(r'^library/',
        include('apiweb.apps.library.urls', namespace='library')),
    url(r'^research/',
        include('apiweb.apps.research.urls', namespace='research')),
    url(r'^publiek/',
        include('apiweb.apps.publiek.urls', namespace='publiek')),
    url(r'^jobs/',
        include('apiweb.apps.jobs.urls', namespace='jobs')),
    url(r'^apo/',
        include('apiweb.apps.apo.urls', namespace='apo')),
    url(r'^internal/account/',
        include('apiweb.apps.internal.account_urls', namespace='account')),
    url(r'^internal/staffmeetings/',
        include('apiweb.apps.staffmeetings.urls', namespace='staffmeetings')),
    url(r'^internal/agenda/',
        include('apiweb.apps.agenda.urls', namespace='agenda')),
    url(r'^internal/apogee/',
        include('apiweb.apps.apogee.urls', namespace='apogee')),
    url(r'^internal/wiki/',
        include('apiweb.apps.wiki.urls', namespace='wiki')),
    url(r'^internal/',
        include('apiweb.apps.internal.urls', namespace='internal')),
    url(r'^wiki/',
        include('apiweb.apps.wiki.viewonly_urls', namespace='wiki2')),
    url(r'^sitemap/', view=SitemapView.as_view(),
        name='sitemap'),
    url(r'^sitemap\.xml$',
        django.contrib.sitemaps.views.sitemap,
        {'sitemaps': sitemaps}),
    url(r'^search/',
        include('apiweb.apps.search.urls', namespace='search')),
    url(r'^about/$',
        view=AboutView.as_view(), name='about'),
    url(r'^24/7/$',
        view=TwentyFourSevenView.as_view(), name='247'),
    url(r'^old/',
        include('apiweb.apps.old.urls', namespace='old')),

    # redirects
    url(r'^scatter/(?P<arguments>.*)$',
        view=ScatterView.as_view(),
        name='scatter'),
    url(r'^home2.html$',
        view=HomeView.as_view(),
        name='home2'),
    url(r'^home.html$',
        view=HomeView.as_view(),
        name='home'),

    # base URL
    url(r'^$',
        MainView.as_view(),
        name='home-page'),
]

apiweb/apps/wiki/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import url
from .views import IndexView, AllView, WikiPageView
from .views import WikiCreateView, WikiEditView, WikiDeleteView

handler500 = 'apiweb.apps.main.errorview.server_error'

urlpatterns = [
    url(r'^view/(?P<name>[-\w]+)/$',
        view=WikiPageView.as_view(),
        name='view'),
    url(r'^edit/(?P<name>[-\w]+)/$',
        view=WikiEditView.as_view(),
        name='edit'),
    url(r'^delete/(?P<name>[-\w]+)/$',
        view=WikiDeleteView.as_view(),
        name='delete'),
    url(r'^create/$',
        view=WikiCreateView.as_view(),
        name='create'),
    url(r'^all/$',
        view=AllView.as_view(),
        name='all'),
    url(r'^$',
        view=IndexView.as_view(),
        name='index'),
]

apiweb/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import include, url
from django.conf import settings
import django.views.static
import sys


handler500 = 'apiweb.apps.main.errorview.server_error'


# Hack to enable the development server to find the media files,
# while keeping those files in the same place as the rest of the
# development
if 'runserver' in sys.argv:
    urlpatterns = [
        # special URLs
        url(r'^media/uploads/staff_meetings/',
            include('apiweb.apps.staffmeetings.media_urls')),
        url(r'^media/(?P<path>.*)$',
            django.views.static.serve,
            {'document_root': settings.MEDIA_ROOT}),
        url(r'^(?P<path>robots.txt)$',
            django.views.static.serve,
            {'document_root': settings.MEDIA_ROOT}),

        # normal URLs
        url(r'^', include('apiweb.apps.urls')),
    ]
else:
    urlpatterns = [url(r'^', include('apiweb.apps.urls'))]

apiweb/apps/staffmeetings/models.py
from __future__ import unicode_literals, absolute_import, division

from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
import os
from datetime import datetime


def get_upload_location(instance, filename):
    filename, extension = os.path.splitext(filename)
    slug = '{}{}'.format(slugify(filename), extension)
    perm_dir = "private" if instance.permission == 0 else "public"
    date = instance.meeting.date.strftime("%Y-%m-%d")
    return os.path.join("uploads", "staff_meetings", date, perm_dir, slug)


class Staffmeeting(models.Model):
    """API staffmeeting"""

    date = models.DateField(_('date staff meeting'), unique=True)

    class Meta:
        verbose_name = _('staff meeting')
        verbose_name_plural = _('staff meetings')
        ordering = ('-date', )

    def __str__(self):
        return "Meeting {}".format(self.date)


class Attachment(models.Model):
    name = models.CharField(max_length=256)
    file = models.FileField(upload_to=get_upload_location,
                            blank=True, null=True)
    permission = models.SmallIntegerField(
        choices=((0, 'private'), (1, 'public')), default=0)
    meeting = models.ForeignKey(Staffmeeting, related_name='attachments')

    def __str__(self):
        permission = "public" if self.permission else "private"
        return "{}-{} ({})".format(self.meeting.date, self.name, permission)

apiweb/apps/staffmeetings/views.py
from __future__ import unicode_literals, absolute_import, division

from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.utils.http import http_date
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import View, ListView
from wsgiref.util import FileWrapper
from ...settings import STAFF_MEDIA_ROOT
from .models import Staffmeeting

import mimetypes
import os
import posixpath
import stat
try:
    from urllib import unquote
except ImportError:  # Python 3
    from urllib.parse import unquote
import time


class IndexView(ListView):
    template_name = 'staffmeetings/staffmeeting_list.html'
    model = Staffmeeting

    def get_queryset(self):
        queryset = self.model.objects.filter(date__year=self.year).order_by(
            '-date')
        return queryset

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)

        can_view = self.request.user.groups.filter(
            name__in=["staff", "secretariat"])
        title = 'Staff meetings at the Anton Pannekoek Institute'

        context['year'] = self.year
        context['title'] = title
        context['staff'] = can_view
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        year = kwargs.get('year', None)
        self.year = int(year) if year is not None else time.localtime()[0]
        # or year = datetime.datetime.now().year
        return super(IndexView, self).dispatch(*args, **kwargs)


class CheckFileView(View):

    def dispatch(self, request, *args, **kwargs):
        path = kwargs.get('path', None)
        if not request.user.is_authenticated():
            raise Http404
        if '/private/' in path:
            if not request.user.groups.filter(
                    name__in=('staff', 'secretariat')):
                raise Http404
        # Clean up given path to only allow serving files below document_root.
        path = posixpath.normpath(unquote(path))
        path = path.lstrip('/')
        newpath = ''
        for part in path.split('/'):
            if not part:
                # Strip empty path components.
                continue
            _, part = os.path.splitdrive(part)
            _, part = os.path.split(part)
            if part in (os.curdir, os.pardir):
                # Strip '.' and '..' in path.
                continue
            newpath = os.path.join(newpath, part).replace('\\', '/')
        if newpath and path != newpath:
            return HttpResponseRedirect(newpath)
        fullpath = os.path.join(STAFF_MEDIA_ROOT, newpath)
        if os.path.isdir(fullpath):
            raise Http404
        if not os.path.exists(fullpath):
            raise Http404
        statobj = os.stat(fullpath)
        mimetype = (mimetypes.guess_type(fullpath)[0] or
                    'application/octet-stream')
#
# file in one chunk
#       contents = open(fullpath, 'rb').read()
# file in chunks of 8 KB
        contents = FileWrapper(open(fullpath))
#
        response = HttpResponse(contents, content_type=mimetype)
        response["Last-Modified"] = http_date(statobj[stat.ST_MTIME])
#
# file in one chunk
#       response["Content-Length"] = len(contents)
# file in chunks of 8 KB
        response["Content-Length"] = os.path.getsize(fullpath)
#
        return response

apiweb/apps/staffmeetings/templates/staffmeetings/base.html
{% extends "base.html" %}
{% block stylesheets %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}staffmeetings/css/staffmeetings.css" />{% endblock stylesheets %}
{% block banner %}<div id="banner"><h1>Institute staff meetings</h1></div>{% endblock banner %}
{% block breadcrumbs %}
{{ block.super }} &#187; <a href="{% url 'staffmeetings:index' %}">Staff meetings</a>
{% endblock breadcrumbs %}
{% block sidemenu %}
{% include "staffmeetings/sidemenu.html" %}
{% endblock sidemenu %}

apiweb/apps/staffmeetings/templates/staffmeetings/sidemenu.html
{% url 'internal:index' as internal_index %}
{% url 'internal:addresses' as internal_addresses %}
{% url 'internal:addresses-phonelist' as internal_addresses_phonelist %}
{% url 'account:login' as account_login %}
{% url 'account:logout' as account_logout %}
{% url 'account:password-change' as account_password_change %}
{% url 'internal:edit-profile' as internal_edit_profile  %}
{% url 'internal:create-profile' as internal_create_profile  %}
{% url 'internal:show-profile' as internal_show_profile  %}
{% url 'internal:observatory' as internal_observatory  %}
{% url 'staffmeetings:index' as staffmeetings_index %}
{% url 'agenda:index' as agenda_index %}
{% url 'apogee:index' as apogee_index %}
{% url 'library:index' as library_index %}
{% url 'internal:logo' as internal_logo %}
{% url 'wiki:view' name="main-wikipage" as wiki_main %}

<ul>
<li> <a {% ifequal request.path internal_index %}class="active" {% endifequal %} href="{{ internal_index }}">Internal</a>
     <ul>
        <li> <a {% ifequal request.path account_login %}class="active" {% endifequal %} href="{{ account_login }}">Login</a> </li>
        <li> <a {% ifequal request.path internal_logout %}class="active" {% endifequal %} href="{{ account_logout }}">Logout</a> </li>
        <li> <a {% ifequal request.path internal_password_change %}class="active" {% endifequal %} href="{{ account_password_change }}">Change Password</a> </li>
        <li> <a {% ifequal request.path internal_edit_profile %}class="active" {% endifequal %}
                {% ifequal request.path internal_create_profile %}class="active" {% endifequal %} href="{{internal_edit_profile}}">Edit Profile</a> </li>
        <li> <a {% ifequal request.path internal_show_profile %}class="active" {% endifequal %} href="{{internal_show_profile}}">Show Profile</a> </li>
        <li> <a {% ifequal request.path internal_addresses %}class="active" {% endifequal %} href="{{ internal_addresses }}">Address list</a> </li>
        <li> <a {% ifequal request.path library_index %}class="active" {% endifequal %}href="{{ library_index }}">Library</a> </li>
        <li> <a {% ifequal request.path internal_observatory %}class="active" {% endifequal %}href="{{ internal_observatory }}">Observatory (apo)</a> </li>
        <li> <a {% ifequal request.path apogee_index %}class="active" {% endifequal %}href="{{ apogee_index }}">APO Agenda</a> </li>
        <li> <a {% ifequal request.path staffmeetings_index %}class="active" {% endifequal %}href="{{ staffmeetings_index }}">API staff meetings</a> </li>
        <li> <a {% ifequal request.path agenda_index %}class="active" {% endifequal %}href="{{ agenda_index }}">API Agenda</a> </li>
        <li> <a {% ifequal request.path internal_logo %}class="active" {% endifequal %}href="{{ internal_logo }}">API logo</a> </li>
        <li> <a {% ifequal request.path wiki_main %}class="active" {% endifequal %}href="{{ wiki_main }}">Wiki</a> </li>
     </ul>
</li>
</ul>

apiweb/apps/staffmeetings/templates/staffmeetings/staffmeeting_list.html
{% extends "staffmeetings/base.html" %}
{% block title %}API - staff meetings{% endblock title %}
{% block contents %}

<h1>{{ title }}</h1>


<a id="prev" href="{% url 'staffmeetings:index' year|add:'-1' %}">&lt;&lt; Prev year</a>
<a id="next" href="{% url 'staffmeetings:index' year|add:'1' %}">Next year &gt;&gt;</a>


{% if not object_list %}
<h2>There have been no staff meetings in {{year}}.</h2>
{% else %}
{% for staffmeeting in object_list %}
<p>
<h2>{{ staffmeeting.date|date:"l j F Y" }}</h2>
<ul>
{% for attachment in staffmeeting.attachments.all %}
{% if staff and attachment.permission == 0 %}
<li> <a href="{{ attachment.file.url }}">{{ attachment.name }}</a></li>
{% endif %}
{% if attachment.permission == 1 %}
<li> <a href="{{ attachment.file.url }}">{{ attachment.name }}</a></li>
{% endif %}
{% endfor %}
</ul>
{% endfor %}
{% endif %}

{% if perms.staffmeetings.change_staffmeeting and perms.staffmeetings.add_staffmeeting %}<div class="edit"><a href="{% url 'admin:index' %}staffmeetings/staffmeeting/add/">add</a> | <a href="{% url 'admin:index' %}staffmeetings/staffmeeting/">edit</a></div>{% endif %}



{% endblock contents %}