apiweb/apps/publiek/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import url
from .views import (StudieView, LinksView, EducatieView, PubliekView,
                    StarnightsView, ApplicationFormView, ThanksView,
                    OnderzoekView, PlanetsView, StarsView, LiveView,
                    RondleidingenView, ExplosionsView, AccretionView,
                    CompactsView, ExtremeView)

handler500 = 'apiweb.main.errorview.server_error'


urlpatterns = [
    url(r'^sterrenkijkavonden/$',
        view=StarnightsView.as_view(),
        name='sterrenkijkavonden'),
    url(r'^rondleidingen/$',
        view=RondleidingenView.as_view(),
        name='rondleidingen'),
    url(r'^aanmeldingsformulier/$',
        view=ApplicationFormView.as_view(),
        name='aanmeldingsformulier'),
    url(r'^thanks/$',
        view=ThanksView.as_view(),
        name='thanks'),
    url(r'^educatie/$',
        view=EducatieView.as_view(),
        name='educatie'),
    url(r'^studie/$',
        view=StudieView.as_view(),
        name='studie'),
    url(r'^links/$',
        view=LinksView.as_view(),
        name='links'),
    url(r'^onderzoek/live/planets/$',
        view=PlanetsView.as_view(),
        name='planets'),
    url(r'^onderzoek/live/stars/$',
        view=StarsView.as_view(),
        name='stars'),
    url(r'^onderzoek/live/$',
        view=LiveView.as_view(),
        name='live'),
    url(r'^onderzoek/extreme/explosions/$',
        view=ExplosionsView.as_view(),
        name='explosions'),
    url(r'^onderzoek/extreme/accretion/$',
        view=AccretionView.as_view(),
        name='accretion'),
    url(r'^onderzoek/extreme/compacts/$',
        view=CompactsView.as_view(),
        name='compacts'),
    url(r'^onderzoek/extreme/$',
        view=ExtremeView.as_view(),
        name='extreme'),
    url(r'^onderzoek/$',
        view=OnderzoekView.as_view(),
        name='onderzoek'),
    url(r'^$',
        view=PubliekView.as_view(),
        name='index'),
]

apiweb/apps/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import include, url
from django.contrib import admin
import django.contrib.sitemaps.views
from .main.sitemap import sitemaps
from .main.views import MainView, HomeView, ScatterView, LowercaseView
from .main.views import SitemapView, AboutView, TwentyFourSevenView
import filebrowser.sites


admin.autodiscover()

urlpatterns = [
    url(r'^.*[A-Z]+.*$',
        view=LowercaseView.as_view(),
        name='redirect-uppercase'),

    url(r'^media/uploads/staff_meetings/',
        include('apiweb.apps.staffmeetings.media_urls')),

    url(r'^admin/filebrowser/',
        include(filebrowser.sites.site.urls)),

    #url(r'^admin/filebrowser/',
    #    include('filebrowser.urls', namespace='filebrowser')),
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # deprecated url(r'^admin/(.*)', admin.site.root, name='admin-root'),
    # to use new setup in templates, use {% url admin:index %}
    url(r'^admin/',
        include(admin.site.urls)),

    url(r'^news/',
        include('apiweb.apps.news.urls', namespace='news')),
    url(r'^people/',
        include('apiweb.apps.people.urls', namespace='people')),
    url(r'^education/',
        include('apiweb.apps.education.urls', namespace='education')),
    url(r'^institute/',
        include('apiweb.apps.institute.urls', namespace='institute')),
    url(r'^library/',
        include('apiweb.apps.library.urls', namespace='library')),
    url(r'^research/',
        include('apiweb.apps.research.urls', namespace='research')),
    url(r'^publiek/',
        include('apiweb.apps.publiek.urls', namespace='publiek')),
    url(r'^jobs/',
        include('apiweb.apps.jobs.urls', namespace='jobs')),
    url(r'^apo/',
        include('apiweb.apps.apo.urls', namespace='apo')),
    url(r'^internal/account/',
        include('apiweb.apps.internal.account_urls', namespace='account')),
    url(r'^internal/staffmeetings/',
        include('apiweb.apps.staffmeetings.urls', namespace='staffmeetings')),
    url(r'^internal/agenda/',
        include('apiweb.apps.agenda.urls', namespace='agenda')),
    url(r'^internal/apogee/',
        include('apiweb.apps.apogee.urls', namespace='apogee')),
    url(r'^internal/wiki/',
        include('apiweb.apps.wiki.urls', namespace='wiki')),
    url(r'^internal/',
        include('apiweb.apps.internal.urls', namespace='internal')),
    url(r'^wiki/',
        include('apiweb.apps.wiki.viewonly_urls', namespace='wiki2')),
    url(r'^sitemap/', view=SitemapView.as_view(),
        name='sitemap'),
    url(r'^sitemap\.xml$',
        django.contrib.sitemaps.views.sitemap,
        {'sitemaps': sitemaps}),
    url(r'^search/',
        include('apiweb.apps.search.urls', namespace='search')),
    url(r'^about/$',
        view=AboutView.as_view(), name='about'),
    url(r'^24/7/$',
        view=TwentyFourSevenView.as_view(), name='247'),
    url(r'^old/',
        include('apiweb.apps.old.urls', namespace='old')),

    # redirects
    url(r'^scatter/(?P<arguments>.*)$',
        view=ScatterView.as_view(),
        name='scatter'),
    url(r'^home2.html$',
        view=HomeView.as_view(),
        name='home2'),
    url(r'^home.html$',
        view=HomeView.as_view(),
        name='home'),

    # base URL
    url(r'^$',
        MainView.as_view(),
        name='home-page'),
]

apiweb/urls.py
from __future__ import unicode_literals, absolute_import, division

from django.conf.urls import include, url
from django.conf import settings
import django.views.static
import sys


handler500 = 'apiweb.apps.main.errorview.server_error'


# Hack to enable the development server to find the media files,
# while keeping those files in the same place as the rest of the
# development
if 'runserver' in sys.argv:
    urlpatterns = [
        # special URLs
        url(r'^media/uploads/staff_meetings/',
            include('apiweb.apps.staffmeetings.media_urls')),
        url(r'^media/(?P<path>.*)$',
            django.views.static.serve,
            {'document_root': settings.MEDIA_ROOT}),
        url(r'^(?P<path>robots.txt)$',
            django.views.static.serve,
            {'document_root': settings.MEDIA_ROOT}),

        # normal URLs
        url(r'^', include('apiweb.apps.urls')),
    ]
else:
    urlpatterns = [url(r'^', include('apiweb.apps.urls'))]

apiweb/apps/publiek/forms.py
from __future__ import unicode_literals, absolute_import, division

from django import forms
from django.core.mail import send_mail
from django.forms.widgets import Input
from django.utils.translation import ugettext_lazy as _
from .models import Starnight, StarnightApplicant


class EmailInput(Input):

    input_type = 'email'


class ApplicationForm(forms.ModelForm):

    date = forms.ModelChoiceField(label=_('Datum'),
                                  queryset=Starnight.objects.filter(
                                      is_registrable=True), empty_label=None)

    email = forms.EmailField(label=_('Email'), widget=EmailInput, required=True)

    def send_email_applicant(self):

        sender = "E.Hanko@uva.nl"
        subject = "Aanmelding voor API sterrenkijkavond"

        date = self.cleaned_data['date']

        recipients = [self.cleaned_data['email']]

        number = self.cleaned_data['number']

        newsletter = self.cleaned_data['newsletter']
        if newsletter == 0: choice = 'niet'
        if newsletter == 1: choice = 'wel'

        message = """\
Goedendag,

U heeft zich aangemeld voor de komende API-sterrenkijkavond ({date}).
U heeft aangegeven dat {visitors} bezoekers deze avond zullen bijwonen.
Vanaf heden ontvangt u {choice} de nieuwsbrief, waarmee u op de hoogte
blijft van de laatste ontwikkelingen omtrent de API-sterrenkijkavonden.

Tot ziens!

Met vriendelijke groet,
Esther Hanko MA
Anton Pannekoek Instituut voor Sterrenkunde
E-mail: E.Hanko@uva.nl
Telnr: +31 (0)20-5258316
        """.format(date=date, visitors=number, choice=choice)

        send_mail(subject, message, sender, recipients, fail_silently=False)


    def send_email_organiser(self):

        sender = "webadmin.api@gmail.com"
        subject = "Nieuwe aanmelding voor de API sterrenkijkavond"

        recipients = ['E.Hanko@uva.nl']
###     recipients = ['martin@science.uva.nl']

        date = self.cleaned_data['date']

        naam = self.cleaned_data['name']
        adres = self.cleaned_data['address']
        postcode = self.cleaned_data['zipcode']
        plaats = self.cleaned_data['city']
        email = self.cleaned_data['email']
        number = self.cleaned_data['number']

        newsletter = self.cleaned_data['newsletter']
        if newsletter == 0: choice = 'Nee'
        if newsletter == 1: choice = 'Ja'

        message = """\
Goedendag,

Er is een nieuwe aanmelding binnen voor de komende \
API-sterrenkijkavond ({date}).
Dit zijn de gegevens:

Naam:     {name}
Adres:    {address}
Postcode: {zipcode}
Plaats:   {city}
E-mail:   {email}

Aantal mensen dat komt: {number}

Wil nieuwsbrief ontvangen: {choice}

Met vriendelijke groet,
Het Apiweb Team
        """.format(date=date, name=naam, address=adres, zipcode=postcode,
                   city=plaats, email=email, number=number, choice=choice)

        send_mail(subject, message, sender, recipients, fail_silently=False)
#
# Just for backup
#
        recipients = ['m.h.m.heemskerk@uva.nl']
        send_mail(subject, message, sender, recipients, fail_silently=False)


    class Meta:
        model = StarnightApplicant
        widgets = {'activity': forms.RadioSelect()}
        fields = ['date', 'name', 'address', 'zipcode', 'city', 'email',
                  'newsletter', 'number']

apiweb/apps/publiek/views.py
from __future__ import unicode_literals, absolute_import, division

from django.views.generic import TemplateView, CreateView
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import Sum
from ..news.models import Press, Event
from .models import Starnight, Activity, StarnightApplicant
from .forms import ApplicationForm


class RondleidingenView(TemplateView):
    template_name = 'publiek/rondleidingen.html'

class EducatieView(TemplateView):
    template_name = 'publiek/educatie.html'

class LinksView(TemplateView):
    template_name = 'publiek/links.html'

class StudieView(TemplateView):
    template_name = 'publiek/studie.html'



class OnderzoekView(TemplateView):
    template_name = 'publiek/onderzoek/index.html'

class PlanetsView(TemplateView):
    template_name = 'publiek/onderzoek/planets.html'

class StarsView(TemplateView):
    template_name = 'publiek/onderzoek/stars.html'

class LiveView(TemplateView):
    template_name = 'publiek/onderzoek/live.html'

class ExplosionsView(TemplateView):
    template_name = 'publiek/onderzoek/explosions.html'

class AccretionView(TemplateView):
    template_name = 'publiek/onderzoek/accretion.html'

class CompactsView(TemplateView):
    template_name = 'publiek/onderzoek/compacts.html'

class ExtremeView(TemplateView):
    template_name = 'publiek/onderzoek/extreme.html'


class PubliekView(TemplateView):
    template_name = 'publiek/index.html'

    def get_context_data(self, **kwargs):
        context = super(PubliekView, self).get_context_data(**kwargs)

        context['press'] = Press.objects.current(days=-180).order_by(
            '-date').filter(language='nl')
        context['events'] = Event.objects.current(days=180).filter(
            language='nl')
        return context


class StarnightsView(TemplateView):
    template_name = 'publiek/starnights/index.html'


class ApplicationFormView(CreateView):
    form_class = ApplicationForm
    template_name = 'publiek/starnights/applicationform.html'
    success_url = reverse_lazy('publiek:thanks')

    def form_valid(self, form):
        form.send_email_applicant()
        form.send_email_organiser()
        return super(ApplicationFormView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ApplicationFormView, self).get_context_data(**kwargs)

        register_open = False
        register_full = False

        nights = Starnight.objects.filter(is_registrable=True)
        if nights.exists():
            register_open = True
            nr_people = 0
            for night in nights:
                stardate = night.date
                star_dict = StarnightApplicant.objects.filter(
                    date__date=stardate).aggregate(Sum('number'))
                if star_dict['number__sum'] is not None:
                    nr_people = star_dict['number__sum']
                if nr_people >= night.max_people: register_full = True
                break

        if register_open and not register_full:
            people1 = {}
            people2 = {}
            people3 = {}
            nr_spots = 0
            nr_activities = 0
            for activity in Activity.objects.all():
                if activity.nr % 10 == 0:
                    if activity.is_in_block1: people1[activity.nr] = ""
                    if activity.is_in_block2: people2[activity.nr] = ""
                    if activity.is_in_block3: people3[activity.nr] = ""
                elif activity.nr > 0:

                    if activity.is_in_block1:
                        nr_people = 0
                        nr_activities += 1
                        star_dict = StarnightApplicant.objects.filter(
                            date__date=stardate).filter(
                                slot1__nr=activity.nr).aggregate(Sum('number'))
                        if star_dict['number__sum'] is not None:
                            nr_people = star_dict['number__sum']
                        if activity.max_people - nr_people == 1:
                            people1[activity.nr] = " 1 plaats beschikbaar"
                            nr_spots += 1
                        elif activity.max_people - nr_people < 1:
                            people1[activity.nr] = " Vol "
                        else:
                            people1[activity.nr] = str(activity.max_people -
                                                       nr_people) + \
                                " plaatsen beschikbaar"
                            nr_spots += activity.max_people - nr_people

                    if activity.is_in_block2:
                        nr_people = 0
                        nr_activities += 1
                        star_dict = StarnightApplicant.objects.filter(
                            date__date=stardate).filter(
                                slot2__nr=activity.nr).aggregate(Sum('number'))
                        if star_dict['number__sum'] is not None:
                            nr_people = star_dict['number__sum']
                        if activity.max_people - nr_people == 1:
                            people2[activity.nr] = " 1 plaats beschikbaar"
                            nr_spots += 1
                        elif activity.max_people - nr_people < 1:
                            people2[activity.nr] = " Vol "
                        else:
                            people2[activity.nr] = str(activity.max_people -
                                                       nr_people) + \
                                " plaatsen beschikbaar"
                            nr_spots += activity.max_people - nr_people

                    if activity.is_in_block3:
                        nr_people = 0
                        nr_activities += 1
                        star_dict = StarnightApplicant.objects.filter(
                            date__date=stardate).filter(
                                slot3__nr=activity.nr).aggregate(Sum('number'))
                        if star_dict['number__sum'] is not None:
                            nr_people = star_dict['number__sum']
                        if activity.max_people - nr_people == 1:
                            people3[activity.nr] = " 1 plaats beschikbaar"
                            nr_spots += 1
                        elif activity.max_people - nr_people < 1:
                            people3[activity.nr] = " Vol "
                        else:
                            people3[activity.nr] = str(activity.max_people -
                                                       nr_people) + \
                                " plaatsen beschikbaar"
                            nr_spots += activity.max_people - nr_people

            if nr_spots < 1 and nr_activities > 0: register_full = True

            context['people1'] = sorted(people1.items())
            context['people2'] = sorted(people2.items())
            context['people3'] = sorted(people3.items())

        context['register_on'] = register_open
        context['register_full'] = register_full

        return context


class ThanksView(TemplateView):
    template_name = 'publiek/starnights/thanks.html'

apiweb/apps/publiek/templates/publiek/onderzoek/accretion.html
{% extends "publiek/onderzoek/base2.html" %}
{% block title %}API - Accretie {% endblock title %}
{% block breadcrumbs %}
{{ block.super }} &#187; <a href="{% url 'publiek:accretion' %}">accretie</a>
{% endblock breadcrumbs %}


{% block contents %}

<h1> De natuurkunde van accretie en accretieschijven </h1>


<h2> Accretie in dubbelsterren </h2>

<p>
Wanneer materie van een begeleidende ster in een dubbelstersysteem wordt
aangetrokken door de zwaartekracht van een compacte ster spreken wij van accretie.
In dubbelsterren komt bij dit proces voornamelijk röntgenstraling vrij.
Met röntgensatellieten wordt de ge-accreteerde materie door astronomen aan
het Anton Pannekoek Instituut bestudeerd, en de eigenschappen van neutronensterren,
zwarte gaten en hun omgeving afgeleid. De ‘gewone’ ster wordt waargenomen
met aardse telescopen die observeren in zichtbaar licht.
</p>

<h2> Accretie en de vorming van jets </h2>

<p>
In dubbelstersystemen waarvan het compacte object een zwart gat is
dat materie aantrekt, kunnen jets worden gedetecteerd. Jets zijn straalstromen
van materie die de ruimte in worden weggeschoten. Het is nog niet duidelijk
waarom jets niet voorkomen bij neutronensterren, en wel bij zwarte gaten.
Aan het Anton Pannekoek Instituut wordt onderzoek gedaan naar de voorwaarden
voor het ontstaan van jets, naar het ontstaansproces waarbij de koppeling
tussen accretie en jets centraal staat en naar de fysische eigenschappen van jets.
Voor dit onderzoek worden modellen en waarnemingen vergeleken.
</p>

<p>
<img src="{{ STATIC_URL }}publiek/images/centaurusA.jpg"></br>
Op deze foto staan het nabije sterrenstelsel Centaurus A en
de tegenovergesteld gerichte jets die door het superzware zwarte gat
in het centrum worden gelanceerd.
De jet linksboven is 13.000 lichtjaar lang.
(credits: X-ray: NASA/CXC/CfA/R.Kraft et al., Radio: NSF/VLA/Univ.
of Hertfordshire/M.Hardcastle et al., Optical: ESO/VLT/ISAAC/M.Rejkuba et al.).
</p>


{% endblock contents %}

apiweb/apps/publiek/templates/publiek/onderzoek/base1.html
{% extends "publiek/base.html" %}
{% block breadcrumbs %}
{{ block.super }} &#187; <a href="{% url 'publiek:onderzoek' %}">Onderzoek</a>
{% endblock breadcrumbs %}

{% block sidemenu %}
{% include "publiek/onderzoek/sidemenu1.html" %}
{% endblock sidemenu %}

apiweb/apps/publiek/templates/publiek/onderzoek/base2.html
{% extends "publiek/base.html" %}
{% block breadcrumbs %}
{{ block.super }} &#187; <a href="{% url 'publiek:onderzoek' %}">Onderzoek</a>
{% endblock breadcrumbs %}

{% block sidemenu %}
{% include "publiek/onderzoek/sidemenu2.html" %}
{% endblock sidemenu %}

apiweb/apps/publiek/templates/publiek/onderzoek/base3.html
{% extends "publiek/base.html" %}
{% block breadcrumbs %}
{{ block.super }} &#187; <a href="{% url 'publiek:onderzoek' %}">Onderzoek</a>
{% endblock breadcrumbs %}

{% block sidemenu %}
{% include "publiek/onderzoek/sidemenu3.html" %}
{% endblock sidemenu %}

apiweb/apps/publiek/templates/publiek/onderzoek/sidemenu1.html
{% url 'publiek:index' as publiek_index %}
{% url 'publiek:sterrenkijkavonden' as publiek_sterrenkijkavonden %}
{% url 'publiek:rondleidingen' as publiek_rondleidingen %}
{% url 'publiek:onderzoek' as publiek_onderzoek %}
{% url 'publiek:live' as publiek_live %}
{% url 'publiek:extreme' as publiek_extreme %}
{% url 'publiek:educatie' as publiek_educatie %}
{% url 'publiek:links' as publiek_links %}
{% url 'publiek:studie' as publiek_studie %}


<ul>
 <li><a {% ifequal request.path publiek_index %}class="active" {% endifequal %}href="{{ publiek_index }}">Publiek</a>
  <ul>
   <li> <a {% ifequal request.path publiek_sterrenkijkavonden %}class="active" {% endifequal %} href="{{ publiek_sterrenkijkavonden }}">Sterrenkijkavonden</a> </li>
   <li> <a {% ifequal request.path publiek_rondleidingen %}class="active" {% endifequal %} href="{{ publiek_rondleidingen }}">Rondleidingen</a> </li>
   <li> <a {% ifequal request.path publiek_onderzoek %}class="active" {% endifequal %} href="{{ publiek_onderzoek }}">Onderzoek</a>
    <ul>
     <li> <a {% ifequal request.path publiek_extreme %}class="active" {% endifequal %} href="{{ publiek_extreme }}">Extreme fysica</a> </li>
       <li> <a {% ifequal request.path publiek_live %}class="active" {% endifequal %} href="{{ publiek_live }}">Op weg naar leven</a> </li>
     </ul>
    </li>
    <li> <a {% ifequal request.path publiek_educatie %}class="active" {% endifequal %} href="{{ publiek_educatie }}">Educatie</a> </li>
    <li> <a {% ifequal request.path publiek_links %}class="active" {% endifequal %} href="{{ publiek_links }}">Links</a> </li>
    <li> <a {% ifequal request.path publiek_studie %}class="active" {% endifequal %}href="{{ publiek_studie }}">Studie</a>
{% ifequal request.path publiek_studie %}
<!--
    <ul>
     <li>Studeren</li>
     <li>Projecten</li>
    </ul>
-->
{% endifequal %}
   </li>
  </ul>
 </li>
</ul>

apiweb/apps/publiek/templates/publiek/onderzoek/sidemenu2.html
{% url 'publiek:index' as publiek_index %}
{% url 'publiek:sterrenkijkavonden' as publiek_sterrenkijkavonden %}
{% url 'publiek:rondleidingen' as publiek_rondleidingen %}
{% url 'publiek:onderzoek' as publiek_onderzoek %}
{% url 'publiek:live' as publiek_live %}
{% url 'publiek:extreme' as publiek_extreme %}
{% url 'publiek:explosions' as publiek_explosions %}
{% url 'publiek:compacts' as publiek_compacts %}
{% url 'publiek:accretion' as publiek_accretion %}
{% url 'publiek:educatie' as publiek_educatie %}
{% url 'publiek:links' as publiek_links %}
{% url 'publiek:studie' as publiek_studie %}


<ul>
 <li><a {% ifequal request.path publiek_index %}class="active" {% endifequal %}href="{{ publiek_index }}">Publiek</a>
  <ul>
   <li> <a {% ifequal request.path publiek_sterrenkijkavonden %}class="active" {% endifequal %} href="{{ publiek_sterrenkijkavonden }}">Sterrenkijkavonden</a> </li>
   <li> <a {% ifequal request.path publiek_rondleidingen %}class="active" {% endifequal %} href="{{ publiek_rondleidingen }}">Rondleidingen</a> </li>
   <li> <a {% ifequal request.path publiek_onderzoek %}class="active" {% endifequal %} href="{{ publiek_onderzoek }}">Onderzoek</a>
     <ul>
      <li> <a {% ifequal request.path publiek_extreme %}class="active" {% endifequal %} href="{{ publiek_extreme }}">Extreme fysica</a>
        <ul>
          <li> <a {% ifequal request.path publiek_explosions %}class="active" {% endifequal %} href="{{ publiek_explosions }}">Explosies</a> </li>
          <li> <a {% ifequal request.path publiek_compacts %}class="active" {% endifequal %} href="{{ publiek_compacts }}">Compacte sterren</a> </li>
          <li> <a {% ifequal request.path publiek_accretion %}class="active" {% endifequal %} href="{{ publiek_accretion }}">Accretie</a> </li>
        </ul>
       </li>
      <li> <a {% ifequal request.path publiek_live %}class="active" {% endifequal %} href="{{ publiek_live }}">Op weg naar leven</a> </li>
     </ul>
   </li>
   <li> <a {% ifequal request.path publiek_educatie %}class="active" {% endifequal %} href="{{ publiek_educatie }}">Educatie</a> </li>
   <li> <a {% ifequal request.path publiek_links %}class="active" {% endifequal %} href="{{ publiek_links }}">Links</a> </li>
   <li> <a {% ifequal request.path publiek_studie %}class="active" {% endifequal %}href="{{ publiek_studie }}">Studie</a>
{% ifequal request.path publiek_studie %}
<!--
    <ul>
     <li>Studeren</li>
     <li>Projecten</li>
    </ul>
-->
{% endifequal %}
   </li>
  </ul>
 </li>
</ul>

apiweb/apps/publiek/templates/publiek/onderzoek/sidemenu3.html
{% url 'publiek:index' as publiek_index %}
{% url 'publiek:sterrenkijkavonden' as publiek_sterrenkijkavonden %}
{% url 'publiek:rondleidingen' as publiek_rondleidingen %}
{% url 'publiek:onderzoek' as publiek_onderzoek %}
{% url 'publiek:live' as publiek_live %}
{% url 'publiek:stars' as publiek_stars %}
{% url 'publiek:planets' as publiek_planets %}
{% url 'publiek:extreme' as publiek_extreme %}
{% url 'publiek:educatie' as publiek_educatie %}
{% url 'publiek:links' as publiek_links %}
{% url 'publiek:studie' as publiek_studie %}


<ul>
 <li><a {% ifequal request.path publiek_index %}class="active" {% endifequal %}href="{{ publiek_index }}">Publiek</a>
  <ul>
   <li> <a {% ifequal request.path publiek_sterrenkijkavonden %}class="active" {% endifequal %} href="{{ publiek_sterrenkijkavonden }}">Sterrenkijkavonden</a> </li>
   <li> <a {% ifequal request.path publiek_rondleidingen %}class="active" {% endifequal %} href="{{ publiek_rondleidingen }}">Rondleidingen</a> </li>
    <ul>
     <li> <a {% ifequal request.path publiek_onderzoek %}class="active" {% endifequal %} href="{{ publiek_onderzoek }}">Onderzoek</a>
      <ul>
       <li> <a {% ifequal request.path publiek_extreme %}class="active" {% endifequal %} href="{{ publiek_extreme }}">Extreme fysica</a> </li>
       <li> <a {% ifequal request.path publiek_live %}class="active" {% endifequal %} href="{{ publiek_live }}">Op weg naar leven</a>
        <ul>
          <li> <a {% ifequal request.path publiek_stars %}class="active" {% endifequal %} href="{{ publiek_stars }}">Sterren</a> </li>
          <li> <a {% ifequal request.path publiek_planets %}class="active" {% endifequal %} href="{{ publiek_planets }}">Planeten</a> </li>
        </ul>
       </li>
      </ul>
     </li>
    </ul>
   <li> <a {% ifequal request.path publiek_educatie %}class="active" {% endifequal %} href="{{ publiek_educatie }}">Educatie</a> </li>
   <li> <a {% ifequal request.path publiek_links %}class="active" {% endifequal %} href="{{ publiek_links }}">Links</a> </li>
   <li> <a {% ifequal request.path publiek_studie %}class="active" {% endifequal %}href="{{ publiek_studie }}">Studie</a>
{% ifequal request.path publiek_studie %}
<!--
    <ul>
     <li>Studeren</li>
     <li>Projecten</li>
    </ul>
-->
{% endifequal %}
   </li>
  </ul>
 </li>
</ul>